[workspace]
members = [
	"chip8/core",
	"chip8/verifier",
	"chip8/bundle",
	"pico8/core",
	"pico8/verifier",
	"pico8/bundle",
	"tic80/core",
	"tic80/verifier",
	"tic80/bundle",
	"chip8/python",
	"pico8/python",
	"tic80/python",
	"conformance",
]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "BSD-3-Clause"
