[workspace]
members = [
	"chip8/core",
	"chip8/verifier",
	"chip8/plugin",
	"hexwell/core",
	"hexwell/verifier",
	"hexwell/plugin",
	"wyrd16/core",
	"wyrd16/verifier",
	"wyrd16/plugin",
	"pico8/core",
	"pico8/verifier",
	"tic80/core",
	"tic80/verifier",
	"chip8/python",
	"hexwell/python",
	"wyrd16/python",
	"conformance",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
