[package]
name = "pico8_core"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
mlua = { version = "0.10.5", features = ["lua54", "vendored", "send"] }
pico8-to-lua = "0.1.1"
pico8_decompress = "0.1.0"
png = "0.17.16"
serde = { version = "1", features = ["derive"] }
sha1 = "0.10"
thiserror = "2"
