[package]
name = "glassvm_machine_conformance"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[dependencies]

[dev-dependencies]
chip8_bundle = { path = "../chip8/bundle" }
glassvm_core = "0.1.0"
glassvm_recorder = "0.1.0"
glassvm_registry = "0.1.0"
pico8_bundle = { path = "../pico8/bundle" }
serde_json = "1"
tic80_bundle = { path = "../tic80/bundle" }
